name = "studio-manager"
main = "worker/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"
# API origin the worker will proxy /api/* to (include scheme and host, no trailing slash)
# Permanent API via Cloudflare Named Tunnel
API_ORIGIN = "https://api.lgger.com"
JWT_SECRET = "change-me-in-production"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Bind a D1 database when ready
[[d1_databases]]
binding = "DB"
database_name = "stm-prod-01"
# Fill in for production deployments
# database_id = "66d2edae-930c-4af2-ac9d-4b0f42c012dc"

[[durable_objects.bindings]]
name = "ROOM_LOCK"
class_name = "RoomLock"