name = "studio-manager"
main = "worker/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"
# JWT_SECRET is managed via `wrangler secret` and should not be set here.

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Bind a D1 database when ready
[[d1_databases]]
binding = "DB"
database_name = "stm-prod-01"
database_id = "66d2edae-930c-4af2-ac9d-4b0f42c012dc"

[[durable_objects.bindings]]
name = "ROOM_LOCK"
class_name = "RoomLock"

[[migrations]]
tag = "v1"
new_classes = ["RoomLock"]

# R2 bucket for storing user avatars
[[r2_buckets]]
binding = "AVATARS"
bucket_name = "stm-avatars-01"