name = "studio-manager"
main = "worker/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"
# API origin the worker will proxy /api/* to (include scheme and host, no trailing slash)
# Permanent API via Cloudflare Named Tunnel
API_ORIGIN = "https://api.lgger.com"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"